frr version 8.4_git
frr defaults traditional
hostname r3
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.3/32
!
route-map ALLOW-ALL permit 10
!
router bgp 65003
 bgp router-id 10.255.0.3
 neighbor 10.0.23.2 remote-as 65002
 !
 address-family ipv4 unicast
  network 10.255.0.3/32
  neighbor 10.0.23.2 activate
  neighbor 10.0.23.2 route-map ALLOW-ALL in
  neighbor 10.0.23.2 route-map ALLOW-ALL out 
exit-address-family
!
