frr version 8.4_git
frr defaults traditional
hostname r2
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.2/32
!
route-map ALLOW-ALL permit 10
!
router bgp 65002
 bgp router-id 10.255.0.2
 neighbor 10.0.12.2 remote-as 65001
 neighbor 10.0.23.3 remote-as 65003
 !
 address-family ipv4 unicast
  network 10.255.0.2/32
  neighbor 10.0.12.2 activate
  neighbor 10.0.23.3 activate
  neighbor 10.0.12.2 route-map ALLOW-ALL in
  neighbor 10.0.12.2 route-map ALLOW-ALL out
  neighbor 10.0.23.3 route-map ALLOW-ALL in
  neighbor 10.0.23.3 route-map ALLOW-ALL out 
exit-address-family
!
